### ISSUE TITLE
app/tools/console not found when updating vendors

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#11]
After I run php tools/vendors I get this output at the end:

`sh: tools/bootstrap: not found`
`sh: app/tools/console: not found`
`sh: app/tools/console: not found`

Why am I missing this files? Why are they run in vendors?

**Comment by pjedrzejewski** [comment]
This will be fixed in next version, the whole vendors script will be replaced with new one. Using **Composer** internally.

**Comment by umpirsky** [comment]
Great, thanks.

**Comment by pjedrzejewski** [comment]
This should be fixed now.
