### ISSUE TITLE
Sandbox configuration

### ISSUE THREAD

**Issue by miklio** [Sylius/Sylius-Sandbox#114]
when i launch the sandbox on my webserver i have this error:

<pre>
ParameterNotFoundException: You have requested a non-existent parameter "sylius_assortment.model.variant.class".
</pre>

when i see the base.yml, this is the configuration:

<pre>
sylius_assortment:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Bundle\SandboxBundle\Entity\Product
            controller: Sylius\Bundle\SandboxBundle\Controller\ProductController
            repository: Sylius\Bundle\SandboxBundle\Repository\ProductRepository
            form: Sylius\Bundle\SandboxBundle\Form\Type\ProductType
        variant:
            model: Sylius\Bundle\SandboxBundle\Entity\Variant
            form: Sylius\Bundle\SandboxBundle\Form\Type\VariantType

</pre>

how is the fix ?

thank u again :+1:

**Comment by umpirsky** [comment]
How did you install your deps, with `composer install` or `composer update`?

BTW, we are moving the development to https://github.com/Sylius/Sylius

**Comment by miklio** [comment]
i do a composer update...
i try to install

**Comment by umpirsky** [comment]
Use install please, since most bundles are updated to use `sylius` prefix in config.

**Comment by miklio** [comment]
ok. And now i use Sylius/ Sylius instead of Sylius / Sylius-Sandbox ?

**Comment by miklio** [comment]
same error with installation...

<pre>
ParameterNotFoundException: You have requested a non-existent parameter "sylius_assortment.model.variant.class".
</pre>
