### ISSUE TITLE
Problem with Assets

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#19]
After fetching the latest sandbox app, I got wrong urls for assets. In page source they look like:

```
<link rel="stylesheet" href="/assets/compiled/frontend_bootstrap.min_1.css" />        
<link rel="stylesheet/less" href="/assets/compiled/frontend_frontend_1.less" />
<script type="text/javascript" src="/assets/compiled/frontend_jquery.min_1.js"></script>
<script type="text/javascript" src="/assets/compiled/frontend_bootstrap.min_2.js"></script>
<script type="text/javascript" src="/assets/compiled/frontend_less-1.1.5.min_3.js"></script>
```

But when I run:

```
 php sylius-sandbox/console assets:install public/

Installing assets for Symfony\Bundle\FrameworkBundle into public/bundles/framework
Installing assets for WhiteOctober\PagerfantaBundle into public/bundles/whiteoctoberpagerfanta
Installing assets for Sylius\Sandbox\Bundle\CoreBundle into public/bundles/sandboxcore
Installing assets for Symfony\Bundle\WebProfilerBundle into public/bundles/webprofiler

```

So they cannot be found. Clearing cache didn't help.

**Comment by pjedrzejewski** [comment]
This is because assets management is handled now by Assetic, use `php sylius-sandbox/console assetic:dump`.

**Comment by umpirsky** [comment]
Thanks.

Shouldn't this work out of the box in dev mode? I thought dump should run only for production.

**Comment by pjedrzejewski** [comment]
Nope, but you can use `--watch` option, so the assets are dumped on every change. Of course it works only with debug mode. =D

**Comment by simshaun** [comment]
It's worth noting that PHP needs to have the openssl extension enabled or the assetic dump will fail upon trying to load https://raw.github.com/nnnick/Chart.js/master/Chart.min.js.

Perhaps that should be added to the installation checklist?
