### ISSUE TITLE
Unrecognized options "mode" under "sylius_catalog.catalogs.assortment"

### ISSUE THREAD

**Issue by mitjade** [Sylius/Sylius-Sandbox#2]
I get this error when I run sylius-sandbox/tools/console doctrine:schema:create

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "mode" under "sylius_catalog.catalogs.assortment"

**Comment by pjedrzejewski** [comment]
I will update the sandbox today, CatalogBundle now guesses the catalog mode, so the option is removed. I will comment here when the update is done.

**Comment by mitjade** [comment]
Great news! Hope you will be able to update the sandbox soon.

**Comment by pjedrzejewski** [comment]
Sandbox is updated, in a few minutes I will upload a package with vendors to Sylius.org, of course you can download deps yourself with `php tools/vendors install`.

**Comment by mitjade** [comment]
It works now!
