### ISSUE TITLE
Themes are not Working

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#20]
In latest sandbox app, as well as [live demo](http://sylius.org/sandbox/) themes are not working. They are activated, but simply not applied, default theme is what I get. I tried to hunt down this bug, but without luck.

**Comment by pjedrzejewski** [comment]
ThemingBundle will be updated soon.

**Comment by pjedrzejewski** [comment]
And it's removed from Sandbox for now, will be back after the update.
