### ISSUE TITLE
Breadcrumb Navigation

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#21]
I noticed something strange in default [breadcrumb navigation](http://i.imgur.com/ufLpo.png).

Isn't it strange to have (in the above case) `Assortment` not clickable, and `Products`. Breadcrumb should have links for pages to go back, and last link should not be clickable and should optional tell me where am I standing at, right?

Example: http://forum.symfony-project.org/viewtopic.php?f=23&t=40393

**Comment by pjedrzejewski** [comment]
Yeah, that was not well-thought, I'll change that or you can submit a PR to fix this. : ) Thanks for noticing!

**Comment by umpirsky** [comment]
I'm not sure how it should be. Sth like https://github.com/Sylius/Sylius-Sandbox/pull/22. I'll maybe make it to work with categories and subcategories in my webshop...
