### ISSUE TITLE
Delete Product Does not Work

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#23]
You can reproduce it on [demo](http://sylius.org/sandbox/administration/assortment/products/list), just click to delete any project, page will just refresh and product will not be deleted..

**Comment by pjedrzejewski** [comment]
This should be fixed now, anyway I removed access to sandbox demo backend. For now at least.

**Comment by umpirsky** [comment]
You can use e.preventDefault() on event object in click handler to prevent default behavior (page refresh) of a link.

**Comment by pjedrzejewski** [comment]
Yeah, that removing of href was stupid, thanks for noticing!
