### ISSUE TITLE
Error when trying to order

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#26]
Error:

```
Catchable Fatal Error: Argument 1 passed to Sylius\Sandbox\Bundle\SalesBundle\Entity\Order::setAddress() must implement interface Sylius\Bundle\AddressingBundle\Model\AddressInterface, array given, called invendor/symfony/symfony/src/Symfony/Component/Form/Util/PropertyPath.php on line 392 and defined in src/Sylius/Sandbox/Bundle/SalesBundle/Entity/Order.php line 49
```

To reproduce:
- Add product to cart.
- Order.
- Fill address info and submit.

**Comment by pjedrzejewski** [comment]
I noticed the issue, but after some investigation I think it's problem with latest Symfony master, the child form returns array instead of object, despite `data_class` option being properly set... I'll be doing some work on sale bundle tomorrow, I'll have a look again.

**Comment by umpirsky** [comment]
I noticed that in Symfony a while ago. A workaround is to pass second parameter to `$this->container->get('form.factory')->create()`. But we should report that to Symfony as well.

**Comment by pjedrzejewski** [comment]
There are two issues about IIRC, pretty annoying as this is one of most important features of Symfony forms, anyway I totally love them.

**Comment by umpirsky** [comment]
Looks like there are no tests for this in `Symfony\Component\Form\Tests\FormFactoryTest`, I'm trying to create one.

**Comment by umpirsky** [comment]
Issue in Symfony is opened 2 months ago, and is still opened. Looks like it will not be fixed any time soon. Maybe we should consider depending on hard version of Symfony in composer.json?

**Comment by pjedrzejewski** [comment]
Our target is 2.1 so we must stay on master branch, AFAIK reverting this commit, which is a big refactoring/improvement of forms doesn't solve the problem. I will think about workaround for this issue just to allow placing orders.

**Comment by umpirsky** [comment]
But this use to work before, maybe in 2.0, I'm not sure. If you are looking for a workaround, just pass empty entity object as a second parameter to `$this->container->get('form.factory')->create()`.

**Comment by pjedrzejewski** [comment]
I will have no time for Sylius till Wednesday. : ( But if you will have some time, PR would be welcome. Thanks bro. Really appreciate your work! Sorry for some slowdowns in development, I wish day was 48 hours. ;)

**Comment by umpirsky** [comment]
Hehe, no problems, I am multitasking too. Will fix PR if I find time ;)

**Comment by pjedrzejewski** [comment]
This will be solved when we get [this](https://github.com/symfony/symfony/pull/3789) merged to Symfony master.

**Comment by umpirsky** [comment]
Solved now.
