### ISSUE TITLE
Call to undefined method Sylius\Bundle\CartBundle\Provider\Provider::resetCart()

### ISSUE THREAD

**Issue by mitjade** [Sylius/Sylius-Sandbox#3]
When I try to place an order, I get this error:

Fatal error: Call to undefined method Sylius\Bundle\CartBundle\Provider\Provider::resetCart() in .../sylius-sandbox/src/Sylius/Sandbox/Bundle/SalesBundle/Processor/Operation/ProcessOperation.php on line 37

**Comment by pjedrzejewski** [comment]
Now it should be temporary fixed, I am working on a quite big refactoring of _SyliusCartBundle_.

**Comment by pjedrzejewski** [comment]
This doesn't affect latest versions of sandbox and cart bundle.
