### ISSUE TITLE
Missing properties: left, right in clas

### ISSUE THREAD

**Issue by mitjade** [Sylius/Sylius-Sandbox#33]
I updated to latest sandbox and when I run php sandbox/console doctrine:schema:create i get:

Missing properties: left, right in class - Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Category

**Comment by pjedrzejewski** [comment]
Looks like I've forgot to update `composer.lock`, run `php composer.phar update` and it should be fixed. I'll update vendors this evening. Thanks for reporting!

**Comment by mitjade** [comment]
Tried that, it did not work. I just reverted the "updates according to categorizer bundle." commit at my end and I was able to continue.

**Comment by pjedrzejewski** [comment]
Should be fixed now, please reopen issue if you have any problems, thanks!
