### ISSUE TITLE
Upgrade to Symfony 2.1

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#37]
There are some changes in form component, it can be fixed with simple find and replace.

From [UPGRADE-2.1.md](https://github.com/symfony/symfony/blob/2cd99e80b6ae03b251c5236202c74113dc6cb39b/UPGRADE-2.1.md)

A third argument $options was added to the methods buildView() and buildViewBottomUp() in FormTypeInterface and FormTypeExtensionInterface. Furthermore, buildViewBottomUp() was renamed to finishView(). At last, all methods in these types now receive instances of FormBuilderInterface and FormViewInterface where they received instances of FormBuilder and FormView before. You need to adapt your implementing classes.

Before:

public function buildForm(FormBuilder $builder, array $options)
public function buildView(FormView $view, FormInterface $form)
public function buildViewBottomUp(FormView $view, FormInterface $form)

After:

public function buildForm(FormBuilderInterface $builder, array $options)
public function buildView(FormViewInterface $view, FormInterface $form, array $options)
public function buildViewBottomUp(FormViewInterface $view, FormInterface $form, array $options)

**Comment by pjedrzejewski** [comment]
I'm working on it right now. =)

**Comment by pjedrzejewski** [comment]
Done!
