### ISSUE TITLE
Upload Product Image Fails

### ISSUE THREAD

**Issue by smuriu** [Sylius/Sylius-Sandbox#59]
Uploading a product image does not seem to work. Tried on the demo site and on a local installation.

When an image is uploaded to a product, nothing happens. The default placeholder is shown and nothing appears in the upload directory.

The upload directory is also not created. Manually creating it seems to have no effect

**Comment by Evgenas** [comment]
Same here

**Comment by Evgenas** [comment]
solved: need create folder uploads/images and media/cache inside public folder. Think add .gitkeep to those folders would be usefull by default

**Comment by pjedrzejewski** [comment]
@Evgenas I like you suggestion, feel free to open a PR or I'll do it later.
Thanks, closing this!
