### ISSUE TITLE
Profiler is always on

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#6]
First of all, thank you for this brilliant tool!

I have  a minor issue, profiler is always displayed, no matter if I work with index.php or dev.php.

This is strange since in index.php there is `$kernel = new \Sylius\SandboxKernel('production', false);`.

How can I fix this?

**Comment by umpirsky** [comment]
Sorry, fixed after clearing the cache.

But it's strange that cache can affect this things.

**Comment by umpirsky** [comment]
But after refresh profiler comes back :)

**Comment by pjedrzejewski** [comment]
Hmmm, that's really strange, I'll look into this issue. : )

**Comment by umpirsky** [comment]
Just for the reference, I downloaded sandbox app from http://sylius.org/downloads/Sylius-Sandbox-0.0.5.zip

Thanks, and keep doing great work, brother from Poland!

**Comment by pjedrzejewski** [comment]
Ah, it's few commits late, I will update the package after I finish big theming refactoring. If you can, download and install the latest version from github, but you must download vendors manually before running installer.php.
Thanks for the good words and cheers! : )

**Comment by umpirsky** [comment]
No problem, I'll play with old version until new one is packaged.

Can you point me to diff where you fixed it, I'm curious? :)

Thanks.

**Comment by pjedrzejewski** [comment]
This shouldn't affect the latest version.
