### ISSUE TITLE
Configurable Currency

### ISSUE THREAD

**Issue by smuriu** [Sylius/Sylius-Sandbox#60]
There are so many places where the currency symbol is shown. It would be helpful to have the currency configurable so that changing the symbol can be done in one place only.

**Comment by Sergic** [comment]
may be need multi-currency support...
need to add new currency, edit, set up default currency, configure exchange index and others options.
this need to add in assort.bundle, cart, order etc.

**Comment by pjedrzejewski** [comment]
I plan to have a separate bundle for that, although I'm not sure if it should be separate one for currencies, and another one for pricing of products, or put it all together in one bundle.

**Comment by umpirsky** [comment]
@pjedrzejewski When you say separate one for pricing of products, what do you mean? Tax, discounts...? Prices are in assortment bundle now.

**Comment by pjedrzejewski** [comment]
Actually, there are no price products in assortment bundle. And I do now want this logic inside sales, nor cart bundle. This should be a separate service which will determine the prices and then we set them on order item, cart item, cart itself or order etc. I want to keep it as simple as possible by default.

**Comment by umpirsky** [comment]
Ah, right, my bad. There is price is in `SandboxAssortmentBundle`.
