### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by PoisonousJohn** [Sylius/Sylius-Sandbox#65]
After installation I got:
Failed to load resource: the server responded with a status of 404 (Not Found) http://sylius.lo/assets/compiled/frontend_bootstrap_1.css

and other assets

Did I missed something?

**Comment by bbeaulant** [comment]
I think that you need to symlink the `vendor/bootstrap` folder in `src/Stylius/Sandbox/CoreBundle/Resources/public`.

**Comment by pjedrzejewski** [comment]
This should be done automatically by composer script handler (inside core bundle). Can you check the symlink?

**Comment by bbeaulant** [comment]
Hmm, right. Maybe it's because my composer script crash during cache clear because I didn't rename parameters.yml.

**Comment by PoisonousJohn** [comment]
Looks like I should somehow compile less resources. How can I do it?

**Comment by pjedrzejewski** [comment]
You need to check if the symlink exists, if yes, then dump assets with assetic. We use compiled versions of Twitters Bootstrap.

**Comment by pjedrzejewski** [comment]
We use CDN now so this should be fixed now, no more symlinks.

**Comment by umpirsky** [comment]
One suggestion here, instead using `http://code.jquery.com/jquery.min.js` we can use `http://code.jquery.com/jquery-1.8.0.min.js` just to know which version we are using.

**Comment by pjedrzejewski** [comment]
:+1:
