### ISSUE TITLE
php sandbox/console assetic:dump error

### ISSUE THREAD

**Issue by Evgenas** [Sylius/Sylius-Sandbox#67]
I'm getting error:

  [Symfony\Component\DependencyInjection\Exception\InactiveScopeException]  
  You cannot create a service ("request") of an inactive scope ("request").  

assetic:dump [--watch] [--force] [--period="..."] [write_to]

when making "php sandbox/console assetic:dump"

**Comment by pjedrzejewski** [comment]
Can you confirm if updating vendors solved the issue?

**Comment by Evgenas** [comment]
Yes all is fine, not sure what was problem...first was tried setup sandbox on my CentOS, had issue with composer install, so was playing with it and after get it working was not able dump assetic...then cloned repo to other cpu with  Ubuntu and somehow all is working there. Suppose messed composer dependencies

PS: just can notice issue with  DataFixtures for Adresses

 $address = $manager->create(); must be changed to  $address = $addressManager->create();  at LoadAddressesData.php line 48

**Comment by pjedrzejewski** [comment]
Good catch, I'll fix it!
