### ISSUE TITLE
Product image fixtures

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#69]
This is part of my plan to make Sylius demo more attractive.

The fix is pretty simple, add product images to fixtures.

**Comment by pjedrzejewski** [comment]
I like the idea! We need to find some nice images with proper licensing yep? For stickers, t-shirts, books and mugs.

**Comment by umpirsky** [comment]
I looked for some nice images. Here is what I found:

Books:

[![](http://farm5.staticflickr.com/4122/5431608389_0975947bbb_m.jpg)](http://www.flickr.com/photos/vfsdigitaldesign/5431608389/)
[![](http://farm3.staticflickr.com/2680/4157904287_b00c37c4bb_m.jpg)](http://www.flickr.com/photos/catnipstudio/4157904287/)
[![](http://farm3.staticflickr.com/2532/4157904273_165c0537ed_m.jpg)](http://www.flickr.com/photos/catnipstudio/4157904273/)
[![](http://farm3.staticflickr.com/2617/4157904245_b1247a5628_m.jpg)](http://www.flickr.com/photos/catnipstudio/4157904245/)
[![](http://farm5.staticflickr.com/4017/4292779189_100f9d1810_m.jpg)](http://www.flickr.com/photos/racum/4292779189/)

Mugs:

[![](http://farm5.staticflickr.com/4014/4260735216_e293da40d9_m.jpg)](http://www.flickr.com/photos/davidspinks/4260735216/)
[![](http://farm8.staticflickr.com/7181/6891342443_e42f72c794_m.jpg)](http://www.flickr.com/photos/nessbypost/6891342443/)
[![](http://farm8.staticflickr.com/7052/6891341973_72352f0c89_m.jpg)](http://www.flickr.com/photos/nessbypost/6891341973/)
[![](http://farm6.staticflickr.com/5110/5645541784_0c5b55de3d_m.jpg)](http://www.flickr.com/photos/june29/5645541784/)
[![](http://farm6.staticflickr.com/5049/5262637757_8de48852a1_m.jpg)](http://www.flickr.com/photos/jellevandebeeck/5262637757/)

T-shirts:

[![](http://farm3.staticflickr.com/2030/2453225588_bd12f72712_m.jpg)](http://www.flickr.com/photos/mikeeperez/2453225588/)
[![](http://farm1.staticflickr.com/231/489117036_a30978bb18_m.jpg)](http://www.flickr.com/photos/dmitry-baranovskiy/489117036/)
[![](http://farm4.staticflickr.com/3187/2869181752_d2ab5f232a_m.jpg)](http://www.flickr.com/photos/juliesjournal/2869181752/)
[![](http://farm4.staticflickr.com/3648/3431261384_ff373b1c90_m.jpg)](http://www.flickr.com/photos/nickstone333/3431261384/)
[![](http://farm2.staticflickr.com/1076/897926489_9cf7728bfb_m.jpg)](http://www.flickr.com/photos/pugusel/897926489/)

Stickers:

[![](http://farm4.staticflickr.com/3440/3963237692_1bfbdd7558_m.jpg)](http://www.flickr.com/photos/stickergiant/3963237692/)
[![](http://farm3.staticflickr.com/2741/4098889008_f93595b93f_m.jpg)](http://www.flickr.com/photos/stickergiant/4098889008/)
[![](http://farm6.staticflickr.com/5013/5393093451_e63c00707d_m.jpg)](http://www.flickr.com/photos/vectorportal/5393093451/)
[![](http://farm5.staticflickr.com/4125/5025968787_6e0980145c_m.jpg)](http://www.flickr.com/photos/vectorportal/5025968787/)
[![](http://farm5.staticflickr.com/4131/4994596090_bb1b58f810_m.jpg)](http://www.flickr.com/photos/lachlanhardy/4994596090/)

We should pick one from each category and use it for fixtures. Of course, you are welcome to suggest images other then posted above.

**Comment by pjedrzejewski** [comment]
I vote for Smashing Mag book, Github mugs (we can use both), First sticker and t-shirt... hm...second or the last one? Nice work man! I'll put them into fixtures.

**Comment by pjedrzejewski** [comment]
Great work @umpirsky! Thanks.
