### ISSUE TITLE
Recent and random products on frontpage

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius-Sandbox#70]
This will make the demo looking more like a shop...

**Comment by umpirsky** [comment]
I have this implemented in my working directories :)

:+1:

**Comment by umpirsky** [comment]
BTW, does this means moving http://sylius.org/sandbox/ to some about page?

**Comment by pjedrzejewski** [comment]
Yeah, maybe we can move it somwhere. I'll think about it.
