### ISSUE TITLE
Default values at product creation form from Variant entity

### ISSUE THREAD

**Issue by Evgenas** [Sylius/Sylius-Sandbox#78]
it looks like default values for Variant entity like AvailableOn (current date), Price (0.00), onHand (1) is not appearing on form when trying to create new product  

I tried add empty_data to setDefaultOptions but it doesn't make effect

Also can't pre-define values before build form cause new product has not variants assigned yet before creation.

**Comment by pjedrzejewski** [comment]
Hey, can you check if this is fixed now? Because works for me with latest assortment bundle. I fixed it [here](https://github.com/Sylius/SyliusAssortmentBundle/commit/1d3fd968a859ef7af1c3bdb1a0b1e473f6bae8cc).

**Comment by Evgenas** [comment]
Have updated your recent changes, updated composer, but still no default values are filled

**Comment by pjedrzejewski** [comment]
Hmmm I see it now. Seems like it worked only for a little period of time. I'll investigate how we can fix it... Thanks for reporting. Please share if you find out anything.

**Comment by pjedrzejewski** [comment]
Fixed! : )
