### ISSUE TITLE
Some installation remarks

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#8]
I tested the installer and noticed few things:
1. Password for database, email...are required, but for some cases in test env, they should be optional.
2. Passwoord should be quoted in config file,  so, instead `sylius.database.password: 1234` it should be `sylius.database.password: '1234'`

**Comment by pjedrzejewski** [comment]
Installer was removed from Sandbox, for now, and probably **InstallerBundle** with **CheckoutsBundle** will be merged into one. Noted the 2 issues for later, thanks!
