### ISSUE TITLE
No css in profiler

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius-Sandbox#9]
There is no css loaded in profiler in dev mode.

There are `/bundles/webprofiler/css/toolbar.css` and `/bundles/webprofiler/css/profiler.css` included, but they don't exist and getting 404.

**Comment by pjedrzejewski** [comment]
Looks like your assets haven't been installed, use `php sylius-sandbox/tools/console-dev assets:install public` command.
I have changed the console to work like in Symfony SE in the latest sandbox and Sylius versions so the commands will be run with `sylius/console foo:bar`.

**Comment by umpirsky** [comment]
Ah, thanks. I thought they need to be installed only in prod mode. That is how it use to work when I last time worked with Symfony. You said that you changed the console, I don't see that on github?

**Comment by pjedrzejewski** [comment]
I will push the changes today with major **SyliusThemingBundle** refactoring. I fixed some of the problems you reported. : )

**Comment by umpirsky** [comment]
Oh, I hope my new theme will work. Is it backward compatible?

**Comment by pjedrzejewski** [comment]
Sure!
